"""adding time spent to user respsponse

Revision ID: 04ce076e0108
Revises: b7c981df3f4f
Create Date: 2021-10-11 21:35:46.037052

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '04ce076e0108'
down_revision = 'b7c981df3f4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Survey Fin', 'timeend')
    op.drop_column('Survey Fin', 'timestart')
    op.add_column('User Response', sa.Column('timespent', sa.Interval(), nullable=True))
    op.drop_column('users', 'is_superuser')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_superuser', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('User Response', 'timespent')
    op.add_column('Survey Fin', sa.Column('timestart', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('Survey Fin', sa.Column('timeend', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
