"""empty message

Revision ID: 57679365eda6
Revises: 60a18927fa0b
Create Date: 2021-10-14 16:39:55.132073

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '57679365eda6'
down_revision = '60a18927fa0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Survey Fin', 'timeend')
    op.drop_column('Survey Fin', 'timestart')
    op.add_column('User Response', sa.Column('timespent', sa.Interval(), nullable=True))
    op.create_unique_constraint(None, 'User Response', ['user_id'])
    op.drop_constraint('User Response_user_id_fkey', 'User Response', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('User Response_user_id_fkey', 'User Response', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'User Response', type_='unique')
    op.drop_column('User Response', 'timespent')
    op.add_column('Survey Fin', sa.Column('timestart', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('Survey Fin', sa.Column('timeend', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
